version: '3'

services:
  api:
    image: cosmtrek/air
    # working_dir value has to be the same of mapped volume
    working_dir: /app
    ports:
      - 5000:5000
    env_file:
      - .env
    volumes:
      - ./:/app/
    networks:
      - default
    depends_on:
      - db
  db:
    image: postgres:14.7
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: standup-management-tool
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    networks:
      - default
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data


networks:
  default:

volumes:
  db_data: